[versions]
agp = "8.3.0-alpha12"
kotlin = "1.9.0"
core-ktx = "1.12.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"
hilt = "2.48"
places = "3.3.0"
retrofit = "2.9.0"
retrofit2-kotlinx-serialization-converter = "1.0.0"
nav-version = "2.7.5"
kotlinx-serialization-json = "1.5.1"
datastore-preferences = "1.0.0"
coil = "2.4.0"
room_version = "2.6.0"
mockk_version = "1.13.8"
exifinterface = "1.3.6"
rules = "1.5.0"
play-services-maps = "18.2.0"
secrets-gradle-plugin = "2.0.1"
mockwebserver = "4.12.0"
kotlinx-coroutines-test = "1.6.4"
play-services-location = "21.0.1"
google-services = "4.4.0"
firebase-bom = "32.6.0"


[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

hilt-android = {group = "com.google.dagger", name = "hilt-android", version.ref = "hilt"}
hilt-android-compiler = {group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt"}

places = { module = "com.google.android.libraries.places:places", version.ref = "places" }
retrofit = {group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
retrofit2-kotlinx-serialization-converter = {group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2-kotlinx-serialization-converter"}

androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "nav-version" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "nav-version" }
navigation-safe-args-gradle-plugin = {group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "nav-version"}
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json"}
androidx-datastore-preference = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences"}
coil = {group = "io.coil-kt", name = "coil", version.ref = "coil"}
room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "room_version" }
room-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "room_version" }
room-ktx = {group = "androidx.room", name = "room-ktx", version.ref = "room_version" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk_version"}
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
mockwebserver = {group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockwebserver"}
kotlinx-coroutines-test = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test"}

play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "play-services-maps" }
secrets-gradle-plugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secrets-gradle-plugin" }

play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt"}
googleServices = {id = "com.google.gms.google-services", version.ref = "google-services"}



